init:
- appveyor version
- lsb_release -a
#- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

test_script:
- sh: |
    PKG_VERSION=$(ls /var/cache/apt/archives/powershell*|head -n1|tr '~' '-')
    PWSH_VERSION=$(pwsh -Command 'Write-Host $PSVersionTable.PSVersion')
    echo 'Installed package:' $PKG_VERSION
    echo '$PSVersionTable Version:' $PWSH_VERSION
    if [[ "$PKG_VERSION" == *"$PWSH_VERSION"* ]]; then
        echo ok;
    else
        echo 'Versions are not the same!'
        return 1
    fi
- ps: |
    [Environment]::GetEnvironmentVariables()

    Write-Error -Message "Error: Too many input values."
    [Console]::Error.WriteLine("This is the output to StdErr")

    for($i = 0; $i -lt 10; $i++) {
        Write-Host "тест $i" -ForegroundColor Yellow -NoNewline
        Start-Sleep -m 200
        Write-Host " ... " -ForegroundColor Green -NoNewline
        Start-Sleep -m 200
        Write-Host " ... " -ForegroundColor Red
        Start-Sleep -m 200
    }

    exit 0

build: off
